### ISSUE TITLE
[bugzilla] Table of bug activity not found

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/perceval#242] opened 2017-12-01 12:46 UTC
The retrieval was stopped due to the following issue:

```bash
2017-11-27 16:06:44,430 - grimoire_elk.arthur - ERROR - Error feeding ocean from bugzilla (https://bugzilla.redhat.com/): Table of bug activity not found.
Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 133, in feed_backend
    ocean_backend.feed()
  File "./grimoire_elk/ocean/elastic.py", line 204, in feed
    for item in items:
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/bugzilla.py", line 111, in fetch
    bug['activity'] = self.__fetch_and_parse_bug_activity(bug_id)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/bugzilla.py", line 201, in __fetch_and_parse_bug_activity
    return [event for event in activity]
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/bugzilla.py", line 201, in <listcomp>
    return [event for event in activity]
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/bugzilla.py", line 346, in parse_bug_activity
    activity_tb = find_activity_table(bs)
  File "/usr/local/lib/python3.4/dist-packages/perceval-0.9.6-py3.4.egg/perceval/backends/core/bugzilla.py", line 327, in find_activity_table
    raise ParseError(cause="Table of bug activity not found.")
perceval.errors.ParseError: Table of bug activity not found.
```

Using `elasticgirl.23`

**Comment by sduenas** [comment] 2017-12-01 13:51
Do you have more info? Which bug did it fail? Which other bugs was it fetching before it failed?

**Comment by albertinisg** [comment] 2017-12-04 13:07
This is all the output I could get :cry: 

How can I see which bug failed?

**Comment by valeriocos** [comment] 2017-12-07 08:50
I'm not able to reproduce the bug. It may be possible that it has been fixed in the upstream server.

**Closed** 2018-01-02 15:14 UTC
Labels: bug
