### ISSUE TITLE
mbox backend fails to parse date

### ISSUE THREAD

**Issue by SaadBinShahid** [grimoirelab/perceval#118] opened 2017-01-30 17:57 UTC
mbox backend fails to parse date. I see the same issue raised for git backend.

git backend fails to parse date #73 @ https://github.com/grimoirelab/perceval/issues/73

Can you please fix it.

Stacktrace ;

```
Traceback (most recent call last):
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/utils.py", line 137, in str_to_datetime
    raise e
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/utils.py", line 130, in str_to_datetime
    dt = parse_datetime(ts)
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/utils.py", line 112, in parse_datetime
    dt = dateutil.parser.parse(ts)
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/mrx/src/ccm/CodeComMerg/mail_to_db.py", line 52, in <module>
    for message in messages:
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backend.py", line 189, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backends/mbox.py", line 93, in fetch
    for message in messages:
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backends/mbox.py", line 137, in _fetch_and_parse_messages
    raise e
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backends/mbox.py", line 117, in _fetch_and_parse_messages
    dt = str_to_datetime(message[MBox.DATE_FIELD])
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/utils.py", line 146, in str_to_datetime
    raise InvalidDateError(date=str(ts))
perceval.errors.InvalidDateError: Fri, 13 Oct 95 09:25 WET DST is not a valid date
```

**Comment by sduenas** [comment] 2017-01-30 18:01
Which version of perceval are you using? This was fixed with 7ffa5de39d18a35945cccaaa04f5228f47cfa3ee

**Comment by SaadBinShahid** [comment] 2017-01-30 18:27
I'm using 0.4.0. I updated it to 0.6.0.dev1. It's my understanding that at the time of the bug fix the version is 0.6.0.dev1. @ https://github.com/grimoirelab/perceval/blob/7ffa5de39d18a35945cccaaa04f5228f47cfa3ee/perceval/_version.py

After updating I get **ImportError: No module named 'perceval.backends.pipermail'**;

```
>>> from perceval.backends.pipermail import Pipermail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'perceval.backends.pipermail'
```

I also tried 0.5.0, which does not give ImportError. But the date bug is still there.

**Comment by SaadBinShahid** [comment] 2017-01-30 18:34
ImportError fixed by changing ;

```
from perceval.backends.pipermail import Pipermail
from perceval.backends.mbox import MBox, MBoxArchive
```

To

```
from perceval.backends.core.pipermail import Pipermail
from perceval.backends.core.mbox import MBox, MBoxArchive
```

So is the date issue.

--------

**Solution: Update perceval version to  0.6.0.dev1**

**Comment by sduenas** [comment] 2017-01-30 18:37
You should remove the contents from `build` directory in your `perceval` repository copy. When you run `setup.py` it creates that directory. The problem is that it stores old versions of the files. Clean that directory running : `./setup.py clean --all` should fix the problem the next time you install from sources.

See my comment here too. This problem is related to a deprecated version with the location of the new modules:
https://github.com/grimoirelab/perceval/issues/114#issuecomment-276108196

**Comment by SaadBinShahid** [comment] 2017-01-30 19:12
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).


```
Traceback (most recent call last):
  File "/home/mrx/src/ccm/CodeComMerg/mail_to_db.py", line 52, in <module>
    for message in messages:
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backend.py", line 359, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backends/core/mbox.py", line 95, in fetch
    for message in messages:
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backends/core/mbox.py", line 139, in _fetch_and_parse_messages
    raise e
  File "/home/mrx/src/ccm/CodeComMerg/venv-ccm/lib/python3.5/site-packages/perceval/backends/core/mbox.py", line 121, in _fetch_and_parse_messages
    if dt < from_date:
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
```

**Comment by sduenas** [comment] 2017-01-31 00:09
To fix this I need to know which mbox you are analyzing. I guess either `dt` or `from_date` are wrong datetimes.

**Comment by jgbarah** [comment] 2017-02-01 12:51
With respect to

> ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).

@SaadBinShahid please open a new issue, to follow it there, since this doesn't seem to be related to the issue reported here.

**Comment by jgbarah** [comment] 2017-02-01 12:55
WRT to the importing of the modules, you are right @SaadBinShahid. I updated the training docs reflecting this for git, and will do for mbox asap. Thanks for reporting.

WRT versions, yes, 5.0.0 causes problems, see #114. If 0.4.0 causes trouble to you, yes, you should use 0.6.0.dev1, and yes, in that case you should use the import line you mention. A 0.6.0 release is on its way.

Since it seems this is clarified for now, I'm closing this ticket.

**Closed by jgbarah** 2017-02-01 12:55 UTC

**Comment by SaadBinShahid** [comment] 2017-02-01 15:58
I wrote a patch for the problem I mentioned above, how to I contribute that ?

**Comment by SaadBinShahid** [comment] 2017-02-01 18:55
Quick start for contributing @ http://perceval.readthedocs.io/en/latest/contributing.html
